version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: postgres_iej
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - journal-network

  mongodb:
    image: mongo:latest
    container_name: mongo_iej
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - journal-network

volumes:
  postgres_data:
  mongodb_data:

networks:
  journal-network:
    driver: bridge